[project]
name = "ladders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.7.1",
    "starlette>=0.45.2",
    "uvicorn>=0.34.0",
    "uvloop>=0.21.0",
]
